[versions]
appVersion = "600"
compileSdkVersion = "33"
minSdkVersion = "21"
targetSdkVersion = "33"
agp = "7.3.1"
kotlin = "1.7.0"
appcompat = "1.5.1"
constraintLayout = "2.1.4"
junit4 = "4.13.2"
androidTestJUnit = "1.1.3"
androidTestRules = "1.4.0"
androidTestEspresso = "3.4.0"
recyclerView = "1.2.1"
hilt = "2.44.2"
hiltCompiler = "1.0.0"
coroutines = "1.5.2"
navigation = "2.5.3"
material = "1.7.0"
lifecycle = "2.5.1"
core= "1.9.0"
junit = "4.13.2"
androidJunit = "1.1.4"
espresso = "3.5.0"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref="appcompat" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref="constraintLayout" }
junit4 = { group = "junit", name = "junit", version.ref="junit4" }
androidTestJUnit = { group = "androidx.test.ext", name = "junit", version.ref="androidTestJUnit" }
androidTestRules = { group = "androidx.test", name = "rules", version.ref="androidTestRules" }
androidTestEspresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref="androidTestEspresso" }
recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref="recyclerView" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref="hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref="hilt" }
hilt-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref="hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref="hiltCompiler" }
coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref="coroutines" }
coroutine-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref="coroutines" }
coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref="coroutines" }
navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref="navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref="navigation" }
material = { group = "com.google.android.material", name = "material", version.ref="material" }
lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref="lifecycle" }
lifecycle-liveData = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref="lifecycle" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref="core" }
junit = { group = "junit", name = "junit", version.ref="junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref="androidJunit" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref="espresso" }
